### ISSUE TITLE
Invalid GRF file generated for 16 colors bitmaps

### ISSUE THREAD

**Issue by dedesite** [AntonioND/architectds#6]
In a .grit file, when using `-gb4` instead of `-gb8` option doesn't seems to work.

When trying to load the .grf, I got an error.

## Step to reproduce

Take for example the `sprites_nitrofs` example from blocksds, modify `ball.grit` this way :

`-gB4 -gt -m! -gzh` instead of `-gB8 -gt -m! -gzh`

Rebuild the project (I know I should also change the color format in the code, but it won't go that far) : 
`python3 build.py`

Try to launch the game : it displays 

> Invalid format in GRF file

I just scratching the surface here, I don't fully understand how archtectds and grit interact and don't know well the .grf format, so I may doing things wrong. I so, I'm sorry for the disturbance.
 
EDIT : BTW Archtectds seems to be a really nice project and simplify A LOT blocksds project's configuration which is helpfull !

**Comment by AntonioND** [comment]
Hi!

I was a bit confused because that example isn't in this repository. 😅

I assume you mean `examples/graphics_2d/sprites_nitrofs` from the SDK repository. In that case, the issue is that the code itself is checking that the format is 8 bit instead of 4 bit:

https://github.com/blocksds/sdk/blob/f56732d51d20571f78e355c2d7fb0dcf18de9c69/examples/graphics_2d/sprites_nitrofs/source/main.c#L66-L70

If you remove that check (or change it) and adapt the code (for example, change `SpriteColorFormat_256Color` to `SpriteColorFormat_16Color`) it should work.

**Comment by AntonioND** [comment]
By the way, there is this other example that may also be helpful!

https://github.com/blocksds/sdk/tree/f56732d51d20571f78e355c2d7fb0dcf18de9c69/examples/graphics_2d/sprites_grf_types

It loads sprites of all supported bit depths.

**Comment by dedesite** [comment]
Oh boy !! I'm sorry for the bug report ! I must be blind really !! I didn't see it was checking for the bit format (here 8) ! Don't understand why I didn't see it... :face_with_head_bandage: (spend some time on it, but it was late...)
Anyway, thanks for your reply and I will have a closer look to the examples in this repo.
